repos:
  - hooks:
      - args:
          - "--profile"
          - black
        id: isort
        stages:
          - commit
    repo: https://github.com/PyCQA/isort
    rev: 5.12.0
  - hooks:
      - args:
          - "-ri"
          - "--remove-all-unused-imports"
          - "--remove-duplicate-keys"
          - "--ignore-init-module-imports"
          - "--remove-unused-variables"
        id: autoflake
        stages:
          - commit
    repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
  - hooks:
      - id: black
        stages:
          - commit
    repo: https://github.com/psf/black
    rev: 23.9.1
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: detect-aws-credentials
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
