version: "3.9"

services:
  web:
    build: web
    command: ./main.py
    ports:
      - "8000:8000"
    volumes:
      - ./web:/app:ro
    environment:
      - PORT=8000
      - DSN=postgres://demo:demo@db:5432/demo?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "demo"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
      start_interval: 5s

volumes:
  postgres_data:
