services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    expose:
      - 6379

  app:
    build: .
    image: ghcr.io/meysam81/currency-store
    environment:
      PORT: "8000"
      REDIS_HOST: redis
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - .:/app:ro
    depends_on:
      - redis
